source "qemu" "vm" {
  cpus                = 4
  accelerator         = "kvm"
  cpu_model           = "host"
  display             = "none"
  use_default_display = false
  disk_image          = false
  efi_boot            = false
  efi_drop_efivars    = false
  format              = "qcow2"
  machine_type        = "q35"
  qemu_binary         = "qemu-system-${var.os_arch}"
  boot_command        = var.boot_command
  boot_wait           = "5s"
  cd_label            = "cidata"
  communicator        = "ssh"
  disk_size           = 65536
  headless            = false
  http_directory      = "${path.root}/http"
  iso_checksum        = var.iso_checksum
  iso_url             = var.iso_url
  memory              = 4096
  shutdown_command    = "echo 'vagrant' | sudo -S shutdown -P now"
  shutdown_timeout    = "15m"
  ssh_password        = "vagrant"
  ssh_port            = 22
  ssh_timeout         = "15m"
  ssh_username        = "vagrant"
  vm_name             = "${var.os_name}-${var.os_version}-amd64"
}
