---
version: "3"
tasks:
  # tool versions
  tool-versions:upgrade:repo:
    summary: Upgrade version in .tool-versions
    desc: Upgrade version in .tool-versions
    internal: true
    silent: true
    cmds:
      - |
        version=$(gh api -H "Accept: application/vnd.github+json" repos/{{ .OWNER }}/{{ .NAME }}/releases/latest | jq .tag_name -r)
        version=${version//v}
        sed -i "s/{{ .NAME }}.*/{{ .NAME }} $version/g" .tool-versions
  tool-versions:upgrade:
    summary: Upgrade versions in .tool-versions
    desc: Upgrade versions in .tool-versions
    cmds:
      - task: tool-versions:upgrade:trivy
      - task: tool-versions:upgrade:task
  tool-versions:upgrade:task:
    summary: Upgrade version of task in .tool-versions
    desc: Upgrade version of task .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: go-task
          NAME: task
  # packer
  fmt:
    summary: Run Packer fmt
    desc: Run Packer fmt
    cmds:
      - packer fmt -var-file=mint-cinnamon-21.2-virtualbox.pkr.hcl core-template-virtualbox.pkr.hcl
      - packer fmt -var-file=mint-cinnamon-21.2-kvm.pkr.hcl core-template-kvm.pkr.hcl
  validate:
    summary: Run Packer validate
    desc: Run Packer validate
    cmds:
      - packer validate -var-file=mint-cinnamon-21.2-virtualbox.pkr.hcl core-template-virtualbox.pkr.hcl
      - packer validate -var-file=mint-cinnamon-21.2-kvm.pkr.hcl core-template-kvm.pkr.hcl
  build:virtualbox:
    summary: Build Linux Mint with VirtualBox Guest Additions
    desc: Build Linux Mint with VirtualBox Guest Additions
    internal: true
    cmds:
      - packer build -var-file=mint-cinnamon-{{ .VERSION }}-virtualbox.pkr.hcl core-template-virtualbox.pkr.hcl
  build:kvm:
    summary: Build Linux Mint
    desc: Build Linux Mint
    internal: true
    cmds:
      - packer build -var-file=mint-cinnamon-{{ .VERSION }}-kvm.pkr.hcl core-template-kvm.pkr.hcl
  build:virtualbox:21.2:
    summary: Build Linux Mint 21.2 with VirtualBox Guest Additions
    desc: Build Linux Mint 21.2 with VirtualBox Guest Additions
    cmds:
      - task: build:virtualbox
        vars:
          VERSION: 21.2
  build:kvm:21.2:
    summary: Build Linux Mint 21.2
    desc: Build Linux Mint 21.2
    cmds:
      - task: build:kvm
        vars:
          VERSION: 21.2
