---
version: "3"
tasks:
  # tool versions
  tool-versions:upgrade:repo:
    summary: Upgrade version in .tool-versions
    desc: Upgrade version in .tool-versions
    internal: true
    silent: true
    cmds:
      - |
        version=$(gh api -H "Accept: application/vnd.github+json" repos/{{ .OWNER }}/{{ .NAME }}/releases/latest | jq .tag_name -r)
        version=${version//v}
        sed -i "s/{{ .NAME }}.*/{{ .NAME }} $version/g" .tool-versions
  tool-versions:upgrade:
    summary: Upgrade versions in .tool-versions
    desc: Upgrade versions in .tool-versions
    cmds:
      - task: tool-versions:upgrade:trivy
      - task: tool-versions:upgrade:task
  tool-versions:upgrade:task:
    summary: Upgrade version of task in .tool-versions
    desc: Upgrade version of task .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: go-task
          NAME: task
  # packer
  fmt:
    summary: Run Packer fmt
    desc: Run Packer fmt
    cmds:
      - packer fmt -var-file=mint-cinnamon-21.3-virtualbox.pkr.hcl core-template-virtualbox.pkr.hcl
      - packer fmt -var-file=mint-cinnamon-21.3-kvm.pkr.hcl core-template-kvm.pkr.hcl
  validate:
    summary: Run Packer validate
    desc: Run Packer validate
    cmds:
      - packer validate -var-file=mint-cinnamon-21.3-virtualbox.pkr.hcl core-template-virtualbox.pkr.hcl
      - packer validate -var-file=mint-cinnamon-21.3-kvm.pkr.hcl core-template-kvm.pkr.hcl
  build:virtualbox:
    summary: Build Linux Mint for VirtualBox
    desc: Build Linux Mint for VirtualBox
    internal: true
    silent: true
    cmds:
      - |
        stty -echo
        read -r -p "Enter Vagrant Cloud token: " VAGRANT_CLOUD_TOKEN
        echo ""
        stty echo
        packer build -var="cloud_token=$VAGRANT_CLOUD_TOKEN" -var-file=mint-cinnamon-{{ .VERSION }}-virtualbox.pkr.hcl core-template-virtualbox.pkr.hcl
  build:kvm:
    summary: Build Linux Mint for KVM
    desc: Build Linux Mint for KVM
    internal: true
    silent: true
    cmds:
      - |
        stty -echo
        read -r -p "Enter Vagrant Cloud token: " VAGRANT_CLOUD_TOKEN
        echo ""
        stty echo
        packer build -var="cloud_token=$VAGRANT_CLOUD_TOKEN" -var-file=mint-cinnamon-{{ .VERSION }}-kvm.pkr.hcl core-template-kvm.pkr.hcl
  build:virtualbox:21.3:
    summary: Build Linux Mint 21.3 for VirtualBox
    desc: Build Linux Mint 21.3 for VirtualBox
    cmds:
      - task: build:virtualbox
        vars:
          VERSION: 21.3
  build:kvm:21.3:
    summary: Build Linux Mint 21.3 for KVM
    desc: Build Linux Mint 21.3 for KVM
    cmds:
      - task: build:kvm
        vars:
          VERSION: 21.3
