---
version: "3"
env:
  DOPPLER_PROJECT: development
tasks:
  # tool versions
  tool-versions:upgrade:repo:
    summary: Upgrade version in .tool-versions
    desc: Upgrade version in .tool-versions
    internal: true
    silent: true
    cmds:
      - |
        version=$(gh api -H "Accept: application/vnd.github+json" repos/{{ .OWNER }}/{{ .NAME }}/releases/latest | jq .tag_name -r)
        version=${version//v}
        sed -i "s/{{ .NAME }}.*/{{ .NAME }} $version/g" .tool-versions
  tool-versions:upgrade:
    summary: Upgrade versions in .tool-versions
    desc: Upgrade versions in .tool-versions
    cmds:
      - task: tool-versions:upgrade:trivy
      - task: tool-versions:upgrade:task
  tool-versions:upgrade:task:
    summary: Upgrade version of task in .tool-versions
    desc: Upgrade version of task .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: go-task
          NAME: task
  # packer
  init:
    summary: Run Packer init
    desc: Run Packer init
    cmds:
      - packer init core-template-kvm.pkr.hcl
  fmt:
    summary: Run Packer fmt
    desc: Run Packer fmt
    cmds:
      - packer fmt -var-file=mint-cinnamon-22.2-kvm.pkrvars.hcl core-template-kvm.pkr.hcl
  validate:
    summary: Run Packer validate
    desc: Run Packer validate
    cmds:
      - packer validate -var-file=mint-cinnamon-22.2-kvm.pkrvars.hcl core-template-kvm.pkr.hcl
  build:kvm:
    summary: Build Linux Mint for KVM
    desc: Build Linux Mint for KVM
    internal: true
    silent: true
    cmds:
      - |
        [ -z "$CODESPACES" ] && export DOPPLER_CONFIG=$(hostname) || export DOPPLER_CONFIG=codespaces
        doppler run -- packer build -var-file=mint-cinnamon-{{ .VERSION }}-kvm.pkrvars.hcl .
  build:kvm:22.2:
    summary: Build Linux Mint 22.2 for KVM
    desc: Build Linux Mint 22.2 for KVM
    cmds:
      - task: build:kvm
        vars:
          VERSION: 22.2
